'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
'
Namespace zarinpal
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PaymentGatewayImplementationServiceBinding", [Namespace]:="http://zarinpal.com/")>  _
    Partial Public Class PaymentGatewayImplementationService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private PaymentRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PaymentVerificationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ZarinpalWebGate.My.MySettings.Default.ZarinpalWebGate_zarinpal_PaymentGatewayImplementationService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event PaymentRequestCompleted As PaymentRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event PaymentVerificationCompleted As PaymentVerificationCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://de.zarinpal.com/pg/services/WebGate/service#PaymentRequest", RequestNamespace:="http://zarinpal.com/", ResponseNamespace:="http://zarinpal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PaymentRequest(ByVal MerchantID As String, ByVal Amount As Integer, ByVal Description As String, ByVal Email As String, ByVal Mobile As String, ByVal CallbackURL As String, ByRef Authority As String) As <System.Xml.Serialization.XmlElementAttribute("Status")> Integer
            Dim results() As Object = Me.Invoke("PaymentRequest", New Object() {MerchantID, Amount, Description, Email, Mobile, CallbackURL})
            Authority = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PaymentRequestAsync(ByVal MerchantID As String, ByVal Amount As Integer, ByVal Description As String, ByVal Email As String, ByVal Mobile As String, ByVal CallbackURL As String)
            Me.PaymentRequestAsync(MerchantID, Amount, Description, Email, Mobile, CallbackURL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PaymentRequestAsync(ByVal MerchantID As String, ByVal Amount As Integer, ByVal Description As String, ByVal Email As String, ByVal Mobile As String, ByVal CallbackURL As String, ByVal userState As Object)
            If (Me.PaymentRequestOperationCompleted Is Nothing) Then
                Me.PaymentRequestOperationCompleted = AddressOf Me.OnPaymentRequestOperationCompleted
            End If
            Me.InvokeAsync("PaymentRequest", New Object() {MerchantID, Amount, Description, Email, Mobile, CallbackURL}, Me.PaymentRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnPaymentRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.PaymentRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PaymentRequestCompleted(Me, New PaymentRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://de.zarinpal.com/pg/services/WebGate/service#PaymentVerification", RequestNamespace:="http://zarinpal.com/", ResponseNamespace:="http://zarinpal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PaymentVerification(ByVal MerchantID As String, ByVal Authority As String, ByVal Amount As Integer, ByRef RefID As Long) As <System.Xml.Serialization.XmlElementAttribute("Status")> Integer
            Dim results() As Object = Me.Invoke("PaymentVerification", New Object() {MerchantID, Authority, Amount})
            RefID = CType(results(1),Long)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PaymentVerificationAsync(ByVal MerchantID As String, ByVal Authority As String, ByVal Amount As Integer)
            Me.PaymentVerificationAsync(MerchantID, Authority, Amount, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PaymentVerificationAsync(ByVal MerchantID As String, ByVal Authority As String, ByVal Amount As Integer, ByVal userState As Object)
            If (Me.PaymentVerificationOperationCompleted Is Nothing) Then
                Me.PaymentVerificationOperationCompleted = AddressOf Me.OnPaymentVerificationOperationCompleted
            End If
            Me.InvokeAsync("PaymentVerification", New Object() {MerchantID, Authority, Amount}, Me.PaymentVerificationOperationCompleted, userState)
        End Sub
        
        Private Sub OnPaymentVerificationOperationCompleted(ByVal arg As Object)
            If (Not (Me.PaymentVerificationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PaymentVerificationCompleted(Me, New PaymentVerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub PaymentRequestCompletedEventHandler(ByVal sender As Object, ByVal e As PaymentRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PaymentRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Authority() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub PaymentVerificationCompletedEventHandler(ByVal sender As Object, ByVal e As PaymentVerificationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PaymentVerificationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property RefID() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Long)
            End Get
        End Property
    End Class
End Namespace
